<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
$fold[1]="1_NO_KHATA";
$fold[2]="2_NO_KHATA";
$fold[3]="3_NO_KHATA"; 
$fold[4]="4_NO_KHATA"; 
$fold[5]="ALLIYA"; 
$fold[6]="BALITARA"; 
$fold[7]="BAMUNBARI_NAPTIPARA"; 
$fold[8]="BANGAON"; 
$fold[9]="BARNARDDI"; 
$fold[10]="BELSOR"; 
$fold[11]="BHANGNAMARI"; 
$fold[12]="CHATAIBARI"; 
$fold[13]="DAKSHIN_BAHJANI"; 
$fold[14]="DAKSHIN_KHETRI_DHARMAPUR"; 
$fold[15]="DAKSHIN_NATUN_DEHAR"; 
$fold[16]="DARKSHIN_MADHYA_DHARMAPUR"; 
$fold[17]="DATARA"; 
$fold[18]="DAULASAL_LARKUCHI"; 
$fold[19]="DEHARKUCHI"; 
$fold[20]="DIHJARI"; 
$fold[21]="GHOGA"; 
$fold[22]="GHOGRAPAR"; 
$fold[23]="JALKHANA_BHATUAKHANA"; 
$fold[24]="JOISAGAR_BARTOLA"; 
$fold[25]="KAKAYA"; 
$fold[26]="KALARCHAR"; 
$fold[27]="KANDHBARI_DAGAPARA"; 
$fold[28]="KEKANKUCHI_KAPLABARI"; 
$fold[29]="KHATIKUCHI"; 
$fold[30]="KURIHAMARI"; 
$fold[31]="LOHARKATHA_ADABARI";
$fold[32]="MADHYA_BAHJANI"; 
$fold[33]="MAKHIBAHA"; 
$fold[34]="MATHURAPUR"; 
$fold[35]="MUGDI_RAMPUR"; 
$fold[36]="MUKALMUA_NARAYANPUR"; 
$fold[37]="Nalbari_town_ward1"; 
$fold[38]="Nalbari_town_ward10"; 
$fold[39]="Nalbari_town_ward11"; 
$fold[40]="Nalbari_town_ward12"; 
$fold[41]="Nalbari_town_ward2"; 
$fold[42]="Nalbari_town_ward3"; 
$fold[43]="Nalbari_town_ward4"; 
$fold[44]="Nalbari_town_ward5"; 
$fold[45]="Nalbari_town_ward6"; 
$fold[46]="Nalbari_town_ward7"; 
$fold[47]="Nalbari_town_ward8"; 
$fold[48]="Nalbari_town_ward9"; 
$fold[49]="NATHKUCHI"; 
$fold[50]="No1_ALLIYA";
$fold[51]="No2_PACHIM_DHARMAPUR"; 
$fold[52]="NO_1_DAKSHIN_POKOWA"; 
$fold[53]="NO_1_UPPER_BARBHAG"; 
$fold[54]="NO_2_CHATAIBARI"; 
$fold[55]="NO_2_DAKSHIN_POKOWA"; 
$fold[56]="NO_2_DATARA"; 
$fold[57]="No_2_PUB_DHARMAPUR"; 
$fold[58]="NO_2_PUB_NAMBARBHAG"; 
$fold[59]="NO_2_UPPER_BARBHAG"; 
$fold[60]="NO_2_UTTAR_PUB_DHARMAPUR"; 
$fold[61]="NO_3_DAKSHIN_POKOWA"; 
$fold[62]="NO_3_UPPER_BARBHAG"; 
$fold[63]="NO_4_DAKSHIN_POKOWA"; 
$fold[64]="NO_4_UPPER_BARBHAG"; 
$fold[65]="NO_5_UPPER_BARBHAG"; 
$fold[66]="NO_6_UPPER_BARBHAG"; 
$fold[67]="PACHIM_BATAHGILA"; 
$fold[68]="PACHIM_DHARMAPUR";
$fold[69]="PACHIM_KHETRI_DHRAMAPUR"; 
$fold[70]="PACHIM_NAMBARBHAG"; 
$fold[71]="PACHIM_NATUN_DEHAR"; 
$fold[72]="PANIGAON"; 
$fold[73]="PUB_BAHJANI";
$fold[74]="PUB_BANBHAG"; 
$fold[75]="PUB_BATAHGILA"; 
$fold[76]="PUB_DHARMAPUR";
$fold[77]="PUB_KHETRI_DHARMAPUR"; 
$fold[78]="PUB_NAMBARBHAG"; 
$fold[79]="PUB_NATUN_DEHAR"; 
$fold[80]="SANEKUCHI"; 
$fold[81]="Tihu_town_ward1"; 
$fold[82]="Tihu_town_ward2"; 
$fold[83]="Tihu_town_ward3"; 
$fold[84]="Tihu_town_ward4"; 
$fold[85]="UTTAR_BAHJANI"; 
$fold[86]="UTTAR_KHETRI_DHARMAPUR"; 
$fold[87]="UTTAR_PUB_DHARMAPUR"; 
for($i=1;$i<=87;$i++){
    $val=$fold[$i];
?>

<a class="nal" href="SECC/Process.asp?subfol=<?php echo $i;?>" style="text-decoration: none"><?php echo $val;?></a>

<?php
echo "<br>";
}
?>